#!/bin/bash

#don't need to do all this shit if we're not interactive
tty -s || return

#SSH_ASKPASS holds `which gnome-ssh-askpass` by default. git calls this
#graphical program even when running on a terminal (a bug). fix like this:
unset SSH_ASKPASS

export EDITOR=`which vim`
export GRAPHICAL_EDITOR="emacsclient"

extract () {
    if [ -f $1 ] ; then
      case $1 in
        *.tar.bz2)   tar xjf $1     ;;
        *.tar.gz)    tar xzf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xf $1      ;;
        *.tbz2)      tar xjf $1     ;;
        *.tgz)       tar xzf $1     ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

source ~/dotfiles/simple_git_prompt.sh

export PATH=${PATH}:~/dotfiles/bin
export PATH=${PATH}:~/.local/bin
export PATH=${PATH}:.

export LD_LIBRARY_PATH=~/.local/lib/:$LD_LIBRARY_PATH

#tricks to quickly clone hosted git repos
github-clone() {
  generic-git-clone "github.com" $*
}
bitbucket-clone() {
  generic-git-clone "bitbucket.org" $*
}
generic-git-clone() {
  host_domain=$1
  if [[ $# -lt 3 ]]; then
    username=bjackman
    repo_name=$2
  else
    username=$2
    repo_name=$3
  fi
  git clone git@${host_domain}:${username}/${repo_name}.git
}

#distro non-specific update
if [[ -f /etc/lsb-release ]]; then
  source /etc/lsb-release
  case $DISTRIB_ID in
    "Ubuntu")
      alias update="sudo apt-get update && sudo apt-get upgrade"
      alias install="sudo apt-get install -y "
      alias uninstall="sudo apt-get remove -y "
      ;;
    "Fedora")
      alias update="sudo yum update"
      alias install="sudo yum install "
      ;;
  esac
else
  if [[ -f /etc/lsb-release-crunchbang ]]; then
    alias update="sudo apt-get update && sudo apt-get upgrade"
    alias install="sudo apt-get install -y "
  fi
fi


newdir() {
  mkdir $1
  cd $1
}

hex2dec() {
  if [ -z `echo $* | grep 0x` ]; then
    printf "%d\n" 0x$*
  else
    printf "%d\n" $*
  fi
}

dec2hex() {
  printf "0x%x\n" $*
}

filegrep() {
  find . -name "$1" -exec grep -nH "$2" {} \;
}

# Mount a disk by label without root
mnt() {
  label=$1
  shift
  udisks --mount /dev/disk/by-label/$label $*
}
umnt() {
  label=$1
  shift
  udisks --unmount /dev/disk/by-label/$label $*
}

alias proper_hexdump="hexdump -v -e '\"0x%08_ax \" 1/4 \"0x%08x\" \"\n\"'"
memdiff() {
  vimdiff <(proper_hexdump $1) <(proper_hexdump $2)
}

alias remove_trailing_whitespace="sed --in-place 's/[[:space:]]\+$//' "

#################
# Git stuff
##################

alias git_add_no_whitespace="git diff -w --no-color | git apply --cached --ignore-whitespace"
git_undo_whitespace() {
  git diff -w --no-color | git apply --cached --ignore-whitespace && \
  git commit -m "tmp"                                             && \
  git reset --hard HEAD                                           && \
  git reset HEAD^
}

alias gap="git add -p "

alias gcam="git commit -am "
alias gcamend="git commit --amend"
alias gcm="git commit -m "

alias gcf="git clean -f "
alias gc="git checkout "
alias gcb="git checkout -b"
alias gcp="git checkout -p "
alias grebase='git rebase -i $(git rev-parse --abbrev-ref @{upstream})'
alias grhard="git reset --hard "
# Stay on the same commit, but with a floating HEAD
alias gfloat='git checkout $(git rev-parse HEAD)'

pretty_log_args="--color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

lg() {
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ $1 != "" ]]; then
        if git rev-parse $1 &>/dev/null; then
            if [[ $2 != "" ]]; then
                range_arg="-n $2"
            fi
            range_arg="$range_arg $1..HEAD"
        else
            range_arg="-n $1"
        fi
    else
        if [ $current_branch == "master" ]; then
            range_arg="-n 30"
        else
            range_arg=master^..HEAD
        fi
    fi

    echo git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit $range_arg
}

####################

find_define() {
  filegrep "*.h" "#define\s*$1"
}
find_type() {
  filegrep "*.h" "typedef.*$1"
}

alias open="xdg-open "
alias fnd="find . -name "
alias gdb="gdb -q"
which sublime 2>&1 > /dev/null || alias sublime="subl"
alias bashrc="source ~/.bashrc"
alias edit_bashrc='$GRAPHICAL_EDITOR ~/dotfiles/my_bashrc'
alias trash="trash-put"
alias webserver="python -m SimpleHTTPServer 8080 "
alias em="emacsclient -n"
alias disassemble='${CROSS_COMPILE}objdump -d '

alias ls="ls --color=auto "

_up() {
  local target
  target=.
  for i in `seq $1`; do
    target=$target/..
  done
  echo $target
}
up() {
  cd $(_up $*)
}
upp() {
  pushd $(_up $*)
}

GERT=1000000000
HISTFILESIZE=$GERT
HISTSIZE=$GERT
shopt -s histappend
HISTCONTROL=ignoredups
HISTIGNORE="ls:bg:fg:history"
shopt -s cmdhist #squash multiline commands into one line (obviously..)

export GREP_OPTIONS="--color=auto"

if [[ -f ~/.local_bashrc ]]; then
  source ~/.local_bashrc
fi

if which fortune > /dev/null && which cowsay > /dev/null; then
    fortune | cowsay
else
    cat <<EOF
 ___________________________
< WHAT IS THIS I DON'T EVEN >
 ---------------------------
        \   ^__^
         \  (@@)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
EOF
fi
