config-asi:
    scripts/config  -e "64BIT" -e CPU_MITIGATIONS \
        -d HYPERV -d CONFIG_PARAVIRT -e MITIGATION_ADDRESS_SPACE_ISOLATION \
        -e CONFIG_LOCALVERSION_AUTO -e  CONFIG_IKCONFIG -e CONFIG_IKCONFIG_PROC \
        -d CONFIG_SYSTEM_TRUSTED_KEYS -d CONFIG_SYSTEM_REVOCATION_KEYS \
        -e CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT -e DEBUG_ENTRY \
        -e VIRTUALIZATION -e KVM -e KVM_INTEL -e KVM_AMD \
        -e BPF_SYSCALL -e BPF_JIT -e DEBUG_INFO_BTF
    make -j olddefconfig
    grep ADDRESS_SPACE_ISOLATION .config

bzimage:
    make -sj100 CC="ccache gcc" KBUILD_BUILD_TIMESTAMP= bzImage compile_commands.json

vmlinux:
    make -sj100 CC="ccache gcc" KBUILD_BUILD_TIMESTAMP= vmlinux compile_commands.json

bindeb:
    make -sj100 CC="ccache gcc" KBUILD_BUILD_TIMESTAMP= bindeb-pkg

asi-qemu extra_args="": bzimage
    vm start  --kernel $PWD/arch/x86_64/boot/bzImage  --image ~/.vmcli/debian-x86_64.img \
        --append_kernel_cmdline="init=/sbin/init-minimal asi=on earlyprintk=ttyS0 nokaslr pti=off" \
        --append_kernel_cmdline={{extra_args}} \
        | tee /tmp/boot.log

asi-qemu-dbg extra_args="": bzimage
    vm start  --kernel $PWD/arch/x86_64/boot/bzImage  --image ~/.vmcli/debian-x86_64.img \
        --append_kernel_cmdline="init=/sbin/init-minimal asi=on earlyprintk=ttyS0 nokaslr pti=off" \
        --append_kernel_cmdline={{extra_args}} \
        --append_qemu_args="-S" \
        | tee /tmp/boot.log
